[package]
name = "toolkitex"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
rmcp = { version = "0.8.0", features = ["server", "transport-streamable-http-server"] }
serde_json = "1.0"
tokio = { version = "1", features = [ "signal", "rt", "rt-multi-thread" ] }