[package]
name = "mcpw_common"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
typify-macro = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing="0.1"
tracing-subscriber = "0.3"

[features]
default = ["mcp_20241105_schema", "debug_log"]
mcp_20241105_schema = []
mcp_20250618_schema = []
# Whether to enable debug trace statements in code (increases binary size by >100K, if small binary really matters to you)
debug_log = []
network_client = []